#cloud-config
preserve_hostname: true

resize_rootfs: false

write_files:
{{ eth1_str }}

{{ growpart_str }}

  - content: |
    # Any text
    path: /etc/growroot-disabled

  - path: /etc/systemd/system/ssh.socket.d/listen.conf
  content: |
    [Socket]
    ListenStream=
    ListenStream={{ ssh_port}}

- path: /etc/configure-ssh.sh
  permissions: '0755'
  content: |
    if systemctl is-active ssh.socket > /dev/null 2>&1
    then
      # OpenSSH is using socket activation
      systemctl disable ssh
      systemctl daemon-reload
      systemctl restart ssh.socket
      systemctl stop ssh
    else
      # OpenSSH is not using socket activation
      sed -i 's/^#*Port .*/Port {{ ssh_port }}/' /etc/ssh/sshd_config
    fi
    systemctl restart ssh


packages: [{{ packages_str }}]

runcmd:
  - [ sgdisk, -e, /dev/sda ]
  - [ partprobe ]
  - [ parted, -s, /dev/sda, mkpart, primary, ext4, "50%", "100%" ]
  - [ growpart, /dev/sda, "1" ]
  - [ resize2fs, /dev/sda1 ]
{{ post_create_commands_str }}
